services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - react-node-challenge-db:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d/    
    
volumes:
  react-node-challenge-db:
